### ISSUE TITLE
Date picker not locale-aware

### ISSUE THREAD

**Issue by bitsofreedom** [DougBeney/pickachu#3] opened 2018-01-14 17:53 UTC
![image](https://user-images.githubusercontent.com/34915492/34918957-2808e3ac-f95c-11e7-9150-a44e1b90ecc6.png)

![image](https://user-images.githubusercontent.com/34915492/34918960-2dc37190-f95c-11e7-98cd-a63f5829b0f1.png)

```
Error detected while processing function Pickachu:
line    4:
Traceback (most recent call last):
  File "/home/bart/dotfiles/vim/.vim/bundle/pickachu/plugin/pickachu.py", line 14, in dateProcess
or
    dateObj = datetime.strptime(input, '%m/%d/%Y')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04-10-17' does not match format '%m/%d/%Y'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/bart/dotfiles/vim/.vim/bundle/pickachu/plugin/pickachu.py", line 121, in MainFuncti
on
    output = runApp(CHOOSEN_APP, CHOOSEN_FORMAT)
  File "/home/bart/dotfiles/vim/.vim/bundle/pickachu/plugin/pickachu.py", line 99, in runApp
    return app['processor'](output.rstrip())
  File "/home/bart/dotfiles/vim/.vim/bundle/pickachu/plugin/pickachu.py", line 16, in dateProcess
or
    dateObj = datetime.strptime(input, '%m/%d/%y')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04-10-17' does not match format '%m/%d/%y'
```
The solution is to use zenity's `--date-format` option.

**Comment by DougBeney** [comment] 2018-01-14 19:58
Thanks for using Pickachu and I greatly appreciate the proposed solution! My last commit should've fixed this issue but I am not 100% certain :)

Please update the plugin and let me know if the issue is gone.

**Comment by bitsofreedom** [comment] 2018-01-14 20:10
Problem still occurs:

![image](https://user-images.githubusercontent.com/34915492/34920207-455b0788-f96f-11e7-8ce6-56897383fc29.png)

You should update your `dateProcessor` function to match the option provided with `--date-format` I believe.

**Comment by DougBeney** [comment] 2018-01-14 20:34
Yep, I did the date format fix previously. 

I just fixed it once more. Turns out I accidentally used hyphens instead of back-slashes 🤦‍♂️ 

Update once more and it should work perfectly 🤞

**Comment by DougBeney** [comment] 2018-01-18 17:48
Hi, @bitsofreedom. Just checking to see if you are still experiencing the issue.

**Comment by DougBeney** [comment] 2018-01-19 18:49
Closing this issue for the meantime because I believe it is solved. If it is not, feel free to let me know and I will reopen.

**Closed as completed by DougBeney** 2018-01-19 18:49 UTC

**Comment by maxigaz** [comment] 2018-01-20 19:49
Hi @DougBeney,

I'm having a similar problem using qarma with Neovim v0.2.2 and KDE Plasma under Manjaro Linux. Here's the output of the error I'm getting:

![nvim_pikachu_20180120_204132](https://user-images.githubusercontent.com/10419911/35187371-4813aa9e-fe23-11e7-99bb-04938032e9f5.png)

The problem occurs regardless of whether I change the value of `let g:pickachu_default_date_format` or not.

**Comment by DougBeney** [comment] 2018-01-21 19:27
@maxigaz Thank you for bringing this issue back up. :)

It turns out that Qarma uses a different date format code than Zenity. I have fixed the issue and pushed an update.

Please update Pickachu via your plugin manager and test it again.

**Comment by maxigaz** [comment] 2018-01-21 20:54
I've just updated and it seems to be working, indeed. Thank you!
